service: helloworld

plugins:
  - serverless-step-functions

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  add:
    handler: handler.add
  
  double:
    handler: handler.double
  
  doubleBigNumber:
    handler: handler.doubleBigNumber

stepFunctions:
  stateMachines:
    simple-maths:
      name: simple-maths
      definition:
        Comment: example to demonstrate function chaining
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource: 
              Fn::GetAtt: [add, Arn]
            Next: Double
          Double: 
            Type: Task
            Resource:
              Fn::GetAtt: [double, Arn]
            End: true
            Retry:
              - ErrorEquals: [NumberIsTooBig]
                MaxAttemps: 0
              - ErrorEquals: [States.ALL]
                MaxAttemps: 3
            Catch:
              - ErrorEquals: [NumberIsTooBig]
                Next: DoubleBigNumber
          DoubleBigNumber:
            Type: Task
            Resource: 
              Fn::GetAtt: [doubleBigNumber, Arn]
            End: true
